# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 366)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 300, 81, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.start_widget = QtWidgets.QWidget(Dialog)
        self.start_widget.setGeometry(QtCore.QRect(30, 10, 381, 101))
        self.start_widget.setObjectName("start_widget")
        self.event_start_label = QtWidgets.QLabel(self.start_widget)
        self.event_start_label.setGeometry(QtCore.QRect(10, 0, 171, 19))
        self.event_start_label.setObjectName("event_start_label")
        self.start_baselineCrossing_radioButton = QtWidgets.QRadioButton(self.start_widget)
        self.start_baselineCrossing_radioButton.setGeometry(QtCore.QRect(10, 20, 181, 23))
        self.start_baselineCrossing_radioButton.setChecked(True)
        self.start_baselineCrossing_radioButton.setObjectName("start_baselineCrossing_radioButton")
        self.start_multiple_radioButton = QtWidgets.QRadioButton(self.start_widget)
        self.start_multiple_radioButton.setGeometry(QtCore.QRect(10, 45, 131, 23))
        self.start_multiple_radioButton.setObjectName("start_multiple_radioButton")
        self.start_fraction_radioButton = QtWidgets.QRadioButton(self.start_widget)
        self.start_fraction_radioButton.setGeometry(QtCore.QRect(10, 70, 191, 23))
        self.start_fraction_radioButton.setObjectName("start_fraction_radioButton")
        self.start_multiple_lineEdit = QtWidgets.QLineEdit(self.start_widget)
        self.start_multiple_lineEdit.setGeometry(QtCore.QRect(140, 47, 113, 17))
        self.start_multiple_lineEdit.setObjectName("start_multiple_lineEdit")
        self.start_fraction_lineEdit = QtWidgets.QLineEdit(self.start_widget)
        self.start_fraction_lineEdit.setGeometry(QtCore.QRect(190, 73, 113, 17))
        self.start_fraction_lineEdit.setObjectName("start_fraction_lineEdit")
        self.end_widget = QtWidgets.QWidget(Dialog)
        self.end_widget.setGeometry(QtCore.QRect(30, 120, 381, 101))
        self.end_widget.setObjectName("end_widget")
        self.event_end_label = QtWidgets.QLabel(self.end_widget)
        self.event_end_label.setGeometry(QtCore.QRect(10, 0, 171, 19))
        self.event_end_label.setObjectName("event_end_label")
        self.end_fraction_lineEdit = QtWidgets.QLineEdit(self.end_widget)
        self.end_fraction_lineEdit.setGeometry(QtCore.QRect(190, 73, 113, 17))
        self.end_fraction_lineEdit.setObjectName("end_fraction_lineEdit")
        self.end_fraction_radioButton = QtWidgets.QRadioButton(self.end_widget)
        self.end_fraction_radioButton.setGeometry(QtCore.QRect(10, 70, 191, 23))
        self.end_fraction_radioButton.setObjectName("end_fraction_radioButton")
        self.end_multiple_radioButton = QtWidgets.QRadioButton(self.end_widget)
        self.end_multiple_radioButton.setGeometry(QtCore.QRect(10, 45, 131, 23))
        self.end_multiple_radioButton.setObjectName("end_multiple_radioButton")
        self.end_multiple_lineEdit = QtWidgets.QLineEdit(self.end_widget)
        self.end_multiple_lineEdit.setGeometry(QtCore.QRect(140, 47, 113, 17))
        self.end_multiple_lineEdit.setObjectName("end_multiple_lineEdit")
        self.end_baselineCrossing_radioButton = QtWidgets.QRadioButton(self.end_widget)
        self.end_baselineCrossing_radioButton.setGeometry(QtCore.QRect(10, 20, 181, 23))
        self.end_baselineCrossing_radioButton.setChecked(True)
        self.end_baselineCrossing_radioButton.setObjectName("end_baselineCrossing_radioButton")
        self.dwelltime_widget = QtWidgets.QWidget(Dialog)
        self.dwelltime_widget.setGeometry(QtCore.QRect(30, 230, 381, 51))
        self.dwelltime_widget.setObjectName("dwelltime_widget")
        self.dwell_time_label = QtWidgets.QLabel(self.dwelltime_widget)
        self.dwell_time_label.setGeometry(QtCore.QRect(10, 0, 171, 19))
        self.dwell_time_label.setObjectName("dwell_time_label")
        self.dwell_baselineCrossing_radioButton = QtWidgets.QRadioButton(self.dwelltime_widget)
        self.dwell_baselineCrossing_radioButton.setGeometry(QtCore.QRect(10, 20, 221, 23))
        self.dwell_baselineCrossing_radioButton.setChecked(True)
        self.dwell_baselineCrossing_radioButton.setObjectName("dwell_baselineCrossing_radioButton")
        self.fwhm_radioButton = QtWidgets.QRadioButton(self.dwelltime_widget)
        self.fwhm_radioButton.setGeometry(QtCore.QRect(260, 20, 131, 23))
        self.fwhm_radioButton.setObjectName("fwhm_radioButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.event_start_label.setText(_translate("Dialog", "Event start threshold:"))
        self.start_baselineCrossing_radioButton.setText(_translate("Dialog", "Baseline crossing"))
        self.start_multiple_radioButton.setText(_translate("Dialog", "Multiple of std"))
        self.start_fraction_radioButton.setText(_translate("Dialog", "Fraction of amplitude"))
        self.event_end_label.setText(_translate("Dialog", "Event end threshold:"))
        self.end_fraction_radioButton.setText(_translate("Dialog", "Fraction of amplitude"))
        self.end_multiple_radioButton.setText(_translate("Dialog", "Multiple of std"))
        self.end_baselineCrossing_radioButton.setText(_translate("Dialog", "Baseline crossing"))
        self.dwell_time_label.setText(_translate("Dialog", "Dwell time:"))
        self.dwell_baselineCrossing_radioButton.setText(_translate("Dialog", "Baseline/Threshold crossing"))
        self.fwhm_radioButton.setText(_translate("Dialog", "FWHM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
